<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gestindem.Application\Gestindem.Application.csproj" />
    <ProjectReference Include="..\Gestindem.Infrastructure\Gestindem.Infrastructure.csproj" />
    <ProjectReference Include="..\Gestindem.Contracts\Gestindem.Contracts.csproj" />
  </ItemGroup>

</Project>
